name: flowkit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State
  get: ^4.6.6
  provider: ^6.1.2

  # Syncfusion
  syncfusion_flutter_charts: ^26.2.14
  syncfusion_flutter_sliders: ^26.2.14
  syncfusion_flutter_core: ^26.2.14
  syncfusion_flutter_calendar: ^26.2.14
  syncfusion_localizations: ^26.2.14
  syncfusion_flutter_maps: ^26.2.14

  desktop_window: ^0.4.0

  # Fl Chart
  fl_chart: ^0.69.0

  # Icons
  flutter_lucide: ^1.4.0
  iconify_flutter: ^0.0.5

  # Storage
  shared_preferences: ^2.3.2

  # Map
  google_maps_flutter: ^2.9.0

  # Font
  google_fonts: ^6.2.1

  # URL
  url_strategy: ^0.3.0
  url_launcher: ^6.3.0

  # Other
  floating_bubbles: ^2.6.2
  metaballs: ^1.5.0
  loading_animation_widget: ^1.2.1
  carousel_slider: ^5.0.0
  overlapped_carousel: ^1.0.2
  intl: ^0.19.0
  quill_html_editor: ^2.2.8
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  colorful_iconify_flutter: ^0.0.2
  appflowy_board: ^0.1.2
  timelines: ^0.1.0
  flutter_reorderable_grid_view: ^5.1.0
  table_calendar: ^3.1.2
  flutter_svg: ^1.1.6
  universal_html: ^2.2.4
  file_picker: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/
    - assets/images/
    - assets/images/avatar/
    - assets/images/logo/
    - assets/images/dummy/
    - assets/images/brand/
    - assets/data/
    - assets/images/products/
    - assets/images/products/bag/
    - assets/images/products/black_shoes/
    - assets/images/products/camera/
    - assets/images/products/face_cream/
    - assets/images/products/girl_sandal/
    - assets/images/products/headphone/
    - assets/images/products/laptop/
    - assets/images/products/perfume/
    - assets/images/products/smart_watch/
    - assets/images/products/watch/
    - assets/images/food/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
